doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            uuid: App\Infrastructure\Shared\Persistence\Doctrine\UuidType

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
